version: '2'
services:
  mgc:
    image: msgraph-cli
    cap_add:
    # https://man7.org/linux/man-pages/man7/capabilities.7.html
    # 
    - IPC_LOCK # Required by gnome-keyring daemon, the dbus secret service